'use client';

import { useEffect, useState } from 'react';
import { Modal } from '@/components/ui';
import type { ReminderStats } from '@/lib/types';

interface Preview {
  to: string[];
  cc: string[];
  from: string;
  replyTo: string;
  subject: string;
  html: string;
  link: string;
  stats: ReminderStats;
  ready: boolean;
  transport: 'smtp' | 'resend' | null;
  blockedReason: string;
  warning: string;
}

const TRANSPORT_LABEL: Record<'smtp' | 'resend', string> = {
  smtp: 'your mail server (SMTP)',
  resend: 'Resend',
};

export default function ReminderModal({
  onClose,
  onSent,
  onError,
}: {
  onClose: () => void;
  onSent: (message: string) => void;
  onError: (message: string) => void;
}) {
  const [preview, setPreview] = useState<Preview | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('/api/reminder', { cache: 'no-store' });
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || 'Could not build the reminder.');
        if (!cancelled) setPreview(json as Preview);
      } catch (err) {
        if (!cancelled) setLoadError(err instanceof Error ? err.message : String(err));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  async function send() {
    setSending(true);
    try {
      const res = await fetch('/api/reminder', { method: 'POST' });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'The reminder could not be sent.');
      const extra = json.cc?.length ? `, cc ${json.cc.length}` : '';
      onSent(`Reminder sent to ${json.to.join(', ')}${extra}`);
    } catch (err) {
      onError(err instanceof Error ? err.message : String(err));
      setSending(false);
    }
  }

  return (
    <Modal
      title="Send reminder to Perfect Choice"
      onClose={onClose}
      wide
      footer={
        <>
          <button type="button" className="btn" onClick={onClose} disabled={sending}>
            Cancel
          </button>
          <button
            type="button"
            className="btn btn-primary"
            onClick={send}
            disabled={sending || !preview?.ready}
          >
            {sending ? 'Sending…' : 'Send now'}
          </button>
        </>
      }
    >
      {loadError ? <p className="modal-error">{loadError}</p> : null}
      {!preview && !loadError ? <p className="muted">Building the reminder…</p> : null}

      {preview ? (
        <>
          <dl className="mail-meta">
            <div>
              <dt>From</dt>
              <dd>{preview.from}</dd>
            </div>
            <div>
              <dt>To</dt>
              <dd>{preview.to.length ? preview.to.join(', ') : <em>not configured</em>}</dd>
            </div>
            {preview.cc.length ? (
              <div>
                <dt>Cc</dt>
                <dd>{preview.cc.join(', ')}</dd>
              </div>
            ) : null}
            {preview.replyTo ? (
              <div>
                <dt>Reply to</dt>
                <dd>{preview.replyTo}</dd>
              </div>
            ) : null}
            <div>
              <dt>Subject</dt>
              <dd>{preview.subject}</dd>
            </div>
            {preview.transport ? (
              <div>
                <dt>Sends via</dt>
                <dd>{TRANSPORT_LABEL[preview.transport]}</dd>
              </div>
            ) : null}
          </dl>

          {!preview.ready ? <p className="modal-error">{preview.blockedReason}</p> : null}
          {preview.ready && preview.warning ? (
            <p className="modal-warn">⚠ {preview.warning}</p>
          ) : null}

          {/* The email body is generated by this app's own template, never by user input. */}
          <iframe
            className="mail-preview"
            title="Reminder email preview"
            sandbox=""
            srcDoc={preview.html}
          />
        </>
      ) : null}
    </Modal>
  );
}
